#!/usr/bin/env python
import logging

import colorama
import coloredlogs
import verboselogs
from colorama import Fore, Style

colorama.init()
verboselogs.install()
coloredlogs.install()

_logger = logging.getLogger('JsonRete')


def main():
    print('%sJsonRete %s0.0.1%s' % (Fore.BLUE, Fore.CYAN, Style.RESET_ALL))
    print()
    while True:
        command = input('%s>>> %s' % (Fore.GREEN, Fore.BLACK))
        if command == 'exit':
            break
        print('%s%s%s' % (Fore.WHITE, command.upper(), Style.RESET_ALL))


if __name__ == '__main__':
    main()
    _logger.verbose('Done.')
