#!/usr/bin/env python
import logging

import coloredlogs
import verboselogs

verboselogs.install()
coloredlogs.install()

_logger = logging.getLogger('JsonRete')

if __name__ == '__main__':
    _logger.notice('Hello, World!')
