#!/usr/bin/env python
import logging

import colorama
import coloredlogs
import verboselogs
from colorama import Fore, Style

colorama.init()
verboselogs.install()
coloredlogs.install()

_logger = logging.getLogger('JsonRete')


def main():
    print('JsonRete 0.0.1')
    print()
    while True:
        command = input('{Fore.GREEN}>>> {Fore.GREY}')
        if command == 'exit':
            break
        print('{Fore.WHITE}%s{Style.RESET_ALL}' % command.upper())


if __name__ == '__main__':
    main()
    _logger.verbose('Done.')
